### ISSUE TITLE
ddescriber not working on intellij 13.1 and jasmine 2.2

### ISSUE THREAD

**Issue by opeled** [andresdominguez/ddescriber#5]
intellij version: 13.1
jasmine: 2.2

When trying to use ddescriber (Ctrl + Shift + D), I get an error.

Error message:
com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;

Error details:
com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;
java.lang.NoSuchMethodError: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;
	at com.karateca.ddescriber.JasmineFinder.createFindModel(JasmineFinder.java:28)
	at com.karateca.ddescriber.JasmineFinder.findAll(JasmineFinder.java:43)
	at com.karateca.ddescriber.model.JasmineFile.createRootNode(JasmineFile.java:79)
	at com.karateca.ddescriber.model.JasmineFile.access$100(JasmineFile.java:22)
	at com.karateca.ddescriber.model.JasmineFile$1.run(JasmineFile.java:39)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:900)
	at com.karateca.ddescriber.ActionUtil.runReadAction(ActionUtil.java:24)
	at com.karateca.ddescriber.model.JasmineFile.buildTreeNodeAsync(JasmineFile.java:36)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction.actionPerformed(JasmineDescribeReplaceAction.java:58)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by andresdominguez** [comment]
Thank you for reporting this issue. I will try to take a look at it tonight. What Java version are you using? Is it Mac/Linux/Windows?

**Comment by opeled** [comment]
OS: Win
java version "1.7.0_60"

10x

**Comment by andresdominguez** [comment]
I just submitted a new version of the plugin that works on Windows. I may take a few days until it gets upgraded. Please download the jar file and install it manually. The new version is 3.2

**Comment by andresdominguez** [comment]
Did it work? Please re-open the issue if it still does not work.

**Comment by opeled** [comment]
Sorry for the late response.
Unfortunately ddescriber V 3.2 did not fix this issue.


Still getting  an error message:
com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;

Details;
om.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;
java.lang.NoSuchMethodError: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;
	at com.karateca.ddescriber.JasmineFinder.createFindModel(JasmineFinder.java:28)
	at com.karateca.ddescriber.JasmineFinder.findAll(JasmineFinder.java:43)
	at com.karateca.ddescriber.model.JasmineFile.createRootNode(JasmineFile.java:79)
	at com.karateca.ddescriber.model.JasmineFile.access$100(JasmineFile.java:22)
	at com.karateca.ddescriber.model.JasmineFile$1.run(JasmineFile.java:39)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:900)
	at com.karateca.ddescriber.ActionUtil.runReadAction(ActionUtil.java:24)
	at com.karateca.ddescriber.model.JasmineFile.buildTreeNodeAsync(JasmineFile.java:36)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction.actionPerformed(JasmineDescribeReplaceAction.java:58)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by yunw** [comment]
I am also having the same issue.

**Comment by andresdominguez** [comment]
I just built a new jar version. I compiled it on a Windows machine. Can you try to install it and let me know if it works?

1. Download this file: https://github.com/andresdominguez/ddescriber/blob/master/ddescriber.jar?raw=true
2. Go to settings > plugins > Install plugin from disk ... and select the file. Restart.

Let me know if it works so I can update the jetbrains repository version.

**Comment by opeled** [comment]
Sorry, still getting an error (a different one).

cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]: cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]

Details:
cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]: cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]
com.intellij.diagnostic.PluginException: cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:287)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:239)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.updateCurrentContext(IdeKeyEventDispatcher.java:679)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:416)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.diagnostic.PluginException: com/karateca/ddescriber/JasmineDescribeReplaceAction : Unsupported major.minor version 52.0 [Plugin: com.karateca.jasmineDescriber]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:262)
	... 13 more
Caused by: java.lang.UnsupportedClassVersionError: com/karateca/ddescriber/JasmineDescribeReplaceAction : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:195)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:191)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 19 more

**Comment by yunw** [comment]
Yes, I am also getting this error as opeled mentioned:

10:07:23 AM PluginException: cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]: cannot create class "com.karateca.ddescriber.JasmineDescribeReplaceAction" [Plugin: com.karateca.jasmineDescriber]

**Comment by bennysce** [comment]
I am still getting this error with Windows 10 IDEA 13.1. ddescriber 3.3 from link above.

12:31:36 NoSuchMethodError: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;: com.intellij.find.FindModel.clone()Lcom/intellij/find/FindModel;
